-   id: jshint
    name: jshint
    entry: jshint
    language: node
    files: \.js$
    args: []

    # Use additional_dependencies to install the actual node package
    additional_dependencies: ['jshint@2.9.4']
    minimum_pre_commit_version: 0.7.0
