- id: js-beautify
  name: js-beautify
  entry: js-beautify --replace --templating django --end-with-newline
  language: node
  'types': [html]
  require_serial: true
  additional_dependencies: ['js-beautify@1.10.3']
